### ISSUE TITLE
Parece no interpretar el símbolo →

### ISSUE THREAD

**Issue by fidel-ml** [FP-BAUM/nuflo#31]
Al intentar  run ["-p", "doc/examples/nats.nu"] 
el resultado es

data Main.Nat where
  Main.Zero : Main.Nat
  Main.Suc : ((PRIM._*** Exception: <stdout>: hPutChar: invalid argument (invalid character)

**Comment by fidel-ml** [comment]
Parecería ser solamente un tema del mostrado...
También me sucede en el Tipado, en el caso de example2.nu.
Quizás se trate solamente de un problema de Windows (si en Linux les funciona)...

**Comment by FedeLochbaum** [comment]
Yes, seems like the `powershell` doesn't use `utf8` as default encoding and then the arrow `->` wasn't being decoding fine.
I updated the readme with some steps to setup the environments in case of use Windows.
